language: cpp

cache: ccache

compiler: clang

dist: bionic

os: linux

# safelist
branches:
    only:
    - master
    - develop

before_install:
#    - sudo apt-get -y install libbz2-dev libfreetype6-dev libpng-dev gtk2.0-dev libnotify-dev libssl-dev libsdl-dev libgtk-3-dev
    - sudo apt-get -y install libgtk-3-dev libnotify-dev libbz2-dev sox libssl-dev

script:
    - ./GenerateCMakeFiles.sh
    - mkdir build.ide
    - cd build.ide
    - cmake -DCMAKE_TOOLCHAIN_FILE=../upp_cmake/utils/toolchain-clang.cmake .. && make -j $(nproc)
    - cd ..

after_success:
    - ./build.ide/bin/ide --version
    - ./build.ide/bin/ide --help
